name: Build
on:
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  sonarcloud:
    name: SonarCloud
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Setup dotnet core
        uses: actions/setup-dotnet@v1
      - name: Install and run dotnet-sonarscanner
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          dotnet tool install --global dotnet-sonarscanner --version 5.0.4
          dotnet sonarscanner begin \
            /k:"appvia_kore-example-apps" \
            /o:"appvia" \
            /d:sonar.host.url="https://sonarcloud.io" \
            /d:sonar.login="$SONAR_TOKEN" \
            /d:sonar.sources="dotnet-hello-world"
          dotnet publish --output out
          dotnet sonarscanner end /d:sonar.login="$SONAR_TOKEN"
